### ISSUE TITLE
Passing blank format generates wrong path

### ISSUE THREAD

**Issue by iuri-gg** [stevenbristol/less-js-routes#3]
Passing blank string as a format causes path to have trailing "dot" in the end. I think your format check function should check for blank string as well as checking for undefined.

for example:
edit_user_path(2,'') //=> /users/2.  

Thanks

**Comment by stevenbristol** [comment]
That's a good point. Can you make that change?

**Comment by iuri-gg** [comment]
Sure. I'll send pull request sometime this afternoon.

On 10/12/11 12:57 PM, "Steven Bristol"
reply@reply.github.com
 wrote:

**Comment by stevenbristol** [comment]
Awesome, thanks!
