### ISSUE TITLE
It doesn't work with a new project

### ISSUE THREAD

**Issue by dejan** [stevenbristol/less-js-routes#6]
``` Ruby
gem 'rails', '3.2.10'
```

I've created new Rails project, added the gem and run

```
rake less:js:routes
```

And got 

```
rake aborted!
No such file or directory - /javascripts/less_routes.js
```

**Comment by stevenbristol** [comment]
LJS isn't aware of the asset pipeline by default. Add this to your config:

  config.output_path = "#{Rails.root}/app/assets/javascripts/less_routes.js"
